"""Definitions for Mikrotik Router sensor entities."""
from dataclasses import dataclass
from homeassistant.helpers.entity import EntityCategory, DeviceInfo
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
    SensorEntityDescription,
)
from homeassistant.const import (
    TEMP_CELSIUS,
    ELECTRIC_POTENTIAL_VOLT,
    POWER_WATT,
    PERCENTAGE,
)


@dataclass
class MikrotikSensorEntityDescriptionAdd:
    """Required values when describing secondary sensor attributes."""

    ha_group: str
    data_path: str
    data_attribute: str
    data_name: str
    data_uid: str
    data_reference: str
    data_attributes_list: []


@dataclass
class MikrotikSensorEntityDescription(
    SensorEntityDescription,
    MikrotikSensorEntityDescriptionAdd,
):
    """Class describing mikrotik entities."""


SENSOR_TYPES = {
    "system_temperature": MikrotikSensorEntityDescription(
        key="system_temperature",
        name="Temperature",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="System",
        data_path="health",
        data_attribute="temperature",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "system_voltage": MikrotikSensorEntityDescription(
        key="system_voltage",
        name="Voltage",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="health",
        data_attribute="voltage",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "system_cpu-temperature": MikrotikSensorEntityDescription(
        key="system_cpu-temperature",
        name="CPU temperature",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="System",
        data_path="health",
        data_attribute="cpu-temperature",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "system_board-temperature1": MikrotikSensorEntityDescription(
        key="system_board-temperature1",
        name="Board temperature",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="System",
        data_path="health",
        data_attribute="board-temperature1",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "system_power-consumption": MikrotikSensorEntityDescription(
        key="system_power-consumption",
        name="Power consumption",
        icon="mdi:transmission-tower",
        native_unit_of_measurement=POWER_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=None,
        ha_group="System",
        data_path="health",
        data_attribute="power-consumption",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "system_fan1-speed": MikrotikSensorEntityDescription(
        key="system_fan1-speed",
        name="Fan1 speed",
        icon="mdi:fan",
        native_unit_of_measurement="RPM",
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="System",
        data_path="health",
        data_attribute="fan1-speed",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "system_fan2-speed": MikrotikSensorEntityDescription(
        key="system_fan2-speed",
        name="Fan2 speed",
        icon="mdi:fan",
        native_unit_of_measurement="RPM",
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="System",
        data_path="health",
        data_attribute="fan2-speed",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "system_uptime": MikrotikSensorEntityDescription(
        key="system_uptime",
        name="Uptime",
        icon=None,
        native_unit_of_measurement=None,
        device_class=SensorDeviceClass.TIMESTAMP,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        ha_group="System",
        data_path="resource",
        data_attribute="uptime",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "system_cpu-load": MikrotikSensorEntityDescription(
        key="system_cpu-load",
        name="CPU load",
        icon="mdi:speedometer",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="System",
        data_path="resource",
        data_attribute="cpu-load",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "system_memory-usage": MikrotikSensorEntityDescription(
        key="system_memory-usage",
        name="Memory usage",
        icon="mdi:memory",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="System",
        data_path="resource",
        data_attribute="memory-usage",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "system_hdd-usage": MikrotikSensorEntityDescription(
        key="system_hdd-usage",
        name="HDD usage",
        icon="mdi:harddisk",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="System",
        data_path="resource",
        data_attribute="hdd-usage",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "traffic_tx": MikrotikSensorEntityDescription(
        key="traffic_tx",
        name="TX",
        icon="mdi:upload-network-outline",
        native_unit_of_measurement="ps",
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="",
        data_path="interface",
        data_attribute="tx-bits-per-second",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "traffic_rx": MikrotikSensorEntityDescription(
        key="traffic_rx",
        name="RX",
        icon="mdi:download-network-outline",
        native_unit_of_measurement="ps",
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="",
        data_path="interface",
        data_attribute="rx-bits-per-second",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "client_traffic_lan_tx": MikrotikSensorEntityDescription(
        key="client_traffic_lan_tx",
        name="LAN TX",
        icon="mdi:upload-network",
        native_unit_of_measurement="tx-rx-attr",
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="",
        data_path="client_traffic",
        data_attribute="lan-tx",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "client_traffic_lan_rx": MikrotikSensorEntityDescription(
        key="client_traffic_lan_rx",
        name="LAN RX",
        icon="mdi:download-network",
        native_unit_of_measurement="tx-rx-attr",
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="",
        data_path="client_traffic",
        data_attribute="lan-rx",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "client_traffic_wan_tx": MikrotikSensorEntityDescription(
        key="client_traffic_wan_tx",
        name="WAN TX",
        icon="mdi:upload-network",
        native_unit_of_measurement="tx-rx-attr",
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="",
        data_path="client_traffic",
        data_attribute="wan-tx",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "client_traffic_wan_rx": MikrotikSensorEntityDescription(
        key="client_traffic_wan_rx",
        name="WAN RX",
        icon="mdi:download-network",
        native_unit_of_measurement="tx-rx-attr",
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="",
        data_path="client_traffic",
        data_attribute="wan-rx",
        data_name="",
        data_uid="",
        data_reference="",
        data_attributes_list=None,
    ),
    "environment": MikrotikSensorEntityDescription(
        key="environment",
        name="",
        icon="mdi:clipboard-list",
        native_unit_of_measurement="",
        device_class=None,
        state_class=None,
        entity_category=None,
        ha_group="Environment",
        data_path="environment",
        data_attribute="value",
        data_name="name",
        data_uid="name",
        data_reference="name",
        data_attributes_list=None,
    ),
}

DEVICE_ATTRIBUTES_CLIENT_TRAFFIC = ["address", "mac-address", "host-name"]
